@startuml
skinparam classAttributeIconSize 0

title [Behavoiral] Command Pattern

class Invoker {
  - _commands : list<Commands*>
  + ~Invoker()
  ..
  + setCommand(Command*)
  + executeCommands()
  + undoCommands()
}
interface Command {
  + {abstract} ~Command()
  ..
  + {abstract} execute()
  + {abstract} undo()
}
class Receiver {
  + action1()
  + action2()
}
class CommandA {
  - _receiver : Receiver*
  --
  + CommandA(Receiver*)
  ..
  + execute()
  + undo()
}
class CommandB {
  - _receiver : Receiver*
  --
  + CommandB(Receiver*)
  ..
  + execute()
  + undo()
}

Invoker o- Command
Command <|.. CommandA
Command <|.. CommandB
Receiver <-u- CommandB
Receiver <-u- CommandA

hide empty members

@enduml