@startuml
skinparam classAttributeIconSize 0

title [Structural] Adapter Pattern

class Target {
    + {abstract} ~Target()
    ..
    + request()
}
class Adapter {
    - _adaptee : Adaptee*
    --
    Adapter(Adaptee*)
    ~Adapter()
    ..
    + request()
}
class Adaptee {
  + specificRequest()
}

Client -> Target
Target <|-- Adapter
Adapter o- Adaptee

hide empty members

@enduml