@startuml
'!pragma layout smetana
'skin rose
skinparam classAttributeIconSize 0

title [Structural] Composite Pattern

class Component {
  + {abstract} ~Component()
  ..
  + add(Component*) {}
  + remove(Component*) {}
  + isComposite() { return false; }
  + {abstract} operation()
}

class Leaf {
  + operation()
}

class Composite {
  # _children: list<Component*>
  + add(Component*)
  + remove(Component*)
  + isComposite() { return true; }
  + operation()
}

Component <|-- Leaf
Component <|-- Composite
Component::add <--o Composite::_children

hide empty members

@enduml