@startuml

title [Creational] Builder Pattern

class Director {
    + construct()
}

interface Builder {
    + {abstract} buildPart()
}

class ConcreteBuilder {
    + buildPart()
    + getResult()
}

'class Product

hide empty members

Director o-r- Builder
Builder <|.d. ConcreteBuilder
ConcreteBuilder .r.> Product

@enduml
