@startuml
skinparam classAttributeIconSize 0

title [Structural] Chain of Responsibility Pattern

abstract Handler {
  # _next : Handler*
  --
  + {abstract} ~Handler()
  ..
  + setNext(Handler*)
  + handle(request)
  # {abstract} canHandle(request)
  # {abstract} process(request)
}
class HanderA {
  + canHandle(request)
  + process(request)
}
class HanderB {
  + canHandle(request)
  + process(request)
}
class HanderC {
  + canHandle(request)
  + process(request)
}
Handler --> Handler
Handler <|-- HanderA
Handler <|-- HanderB
Handler <|-- HanderC 

hide empty members

@enduml