@startuml
'left to right direction
skinparam classAttributeIconSize 0

title [Structural] Decorator Pattern

interface Component {
    + {abstract} ~Component()
    ..
    + {abstract} operation()
}
class ConcreteComponent {
    + operation()
}
class Decorator {
    # _component : Component*
    --
    + {abstract} ~Decorator
    ..
    + operation()
}
class DecoratorA {
    + DecoratorA(Component*)
    ..
    + operation()
}
class DecoratorB {
    + DecoratorA(Component*)
    ..
    + operation()
}

Component <|.. ConcreteComponent
Component <|.. Decorator
Component::operation --o Decorator
Decorator <|-- DecoratorA
Decorator <|-- DecoratorB

hide empty members

@enduml